name: sneakerv1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/nike.png
    - assets/images/Air Jordan 1.png
    - assets/images/ZoomFreak.png
    - assets/images/KDTrey.png
    - assets/images/Kyrie6.png